spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cloud_gateway_eureka
    username: postgres
    password: krya

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: payment-service

server:
  port: 8082
  servlet:
    context-path: /payment-service


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka  # URL where other Eureka clients can register and discover services

#  instance:
#    hostname: localhost



