spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cloud_gateway_eureka
    username: postgres
    password: krya

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: order-service

server:
  port: 8081
  servlet:
    context-path: /order-service


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka

#  instance:
#    hostname: localhost


